language: scala
scala:
- 2.13.4
before_install:
- bash scripts/decrypt_files_if_not_pr.sh
before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.coursier/cache -name "*.lock" -type f -delete
cache:
  directories:
  - "$HOME/.sbt/1.0"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/cache"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"
script:
- sbt ++$TRAVIS_SCALA_VERSION test
deploy:
- provider: script
  script: sbt publishRelease && bash scripts/docker_push.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+(\\.[0-9]+)?"
env:
  global:
  - secure: HraW555rI8osLDb1NiSMoPfwfNQcQPnIuYFIugDdWIs8EZum+muPKAY0fbj8euOSK8oSeHxsXOwZ9R4ZCYKF4ju+TWQdEgBx8bn4cRxXQxmQtqRqiUdHz5vEQ6yyjkhhTgTmQr7TVzuQWPR0hxWrdYmALVls5LGviAISyeZJH6yc+K9l13Xwd23Ockfd99XlKr6zwAdmZozlpyNDtHffrYYcXpwTG4cK3WiqMjrPW9SEaKqHW83iAQQaqdK+uW7Oqn9bN1CMuLzLqS1lwlnv+R5+EzOD/w1GLuHYxyQeUthgtCuFNg+5Fz9G2wbykeatBXVR5cm16UTvSidsr2rpDDDmDF2xP8VNUX0bz7TEDa5Qaygt0zCDwGP/n7m3FJiLQyrTAFgwX8Z/+tEkujEEde4/qtMiPTpESJqblrUtIHkjg9prKyUZAqh86AQEKOzxLslqmEB8hmnP+6tQwKrVvLXy2jtuGGgBEx0G/kn0VKRmsZRWkAcdzJQq9NEqxcVsiapFKxIxPVx3ixLGwYJ8kh/Aag1TV9Cta398zDDlYJNPY/vyXo9b1ePbSMWck3WBwlKYxK2vm3ur+ieWvMw/ccUUzd55ydaOaZkooXowJIt8wyJ83oBx12SIKodCUlRV+Z5bcFQCmJXwDc0LrAP0JGgOvYIHdpAGxFGBpRbiGlg=
  - secure: c/ImfS92WdkVxJQh75YAeAU/OIjnXJUpl3QWQ05AURBM3GdtI2vgMaIcJbM1qF1A+uGsrwH6YBrudlq3g0OIyVJ55U7IheuHE/RDHTBSCkUTLI9wpxUJYB9F+WgIfrOnYqZ/nfLPXJuefohMYS3zL3F/Fw+SwQPg0io161IvcJHjAchwQCBOVGkIYGiNsxEgxX1/p15Id8IcRswTJ+cPRrMNMWYzAUkKJ96YkT+jy/+E5YfADEhFbzrUW/b9hHiuvdZb4DA5SbOQkUzpQBCeeacsj6dWZ0xwf0RynhDH2iubi4fR/ausNYcNC2MTXJePRbC2I3cZ3+iwpDG/TVpFF8XSWqqVrotfQQPF6cJ3qv8VSHJMiWBVf+/W1aWCbrqznSua1PnOESDQCJ/W/z2JOa/i5EAnT8wXYA1fuSZ3QvMHIYyTBm3jiIAiWGrl57AebEtpqn1xvVt4SUpijILCupgC0XUtKPA2VkiyLo2am4e6DNuuUfeL1+5kaIoC9VDDvlpX2UCTnyTH9Wm/SMDgyOWfeLJsLMkfCthtd5dqXxdQW01V16hIDsVY/SRJDUMPPowp1Gdef3fE5Kt/DRmu/zYqePEYvmEiE8dYr+4HqWccsoNw6WNnMMccP+Zh72cUD3d5ieT9SEfZoItefD2+wK3aICNAHoJbbDP4tAkVY7Y=
